version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 10
    reviewers:
      - Ensono/stacks-maintainers
    assignees:
      - RichardSlater
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
    groups:
      low-risk:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"
    cooldown:
      default-days: 5
